### ISSUE TITLE
Can you add new topics in this repository?

### ISSUE THREAD

**Issue by Neustradamus** [naqvis/cr-xmpp#6]
@naqvis: I wish you a Happy New Year!

Can you add new topics in this repository like others?
- scram
- scram-sha-1
- scram-sha-256
- scram-sha-512

Thanks in advance.

**Comment by naqvis** [comment]
Thanks @Neustradamus. Wishing you Happy New Year as well.
> 
> Can you add new topics in this repository like others?
> 
>     * scram
> 
>     * scram-sha-1
> 
>     * scram-sha-256
> 
>     * scram-sha-512
> 
> 
> Thanks in advance.

All of cited scram are already implemented in this shard.

**Comment by Neustradamus** [comment]
@naqvis: In topic section of the repository, at right here, click on the gear: https://github.com/naqvis/cr-xmpp

**Comment by naqvis** [comment]
Thanks and updated repo topic section.

**Comment by Neustradamus** [comment]
@naqvis: Thanks for your wishes, and thanks for the adding! :)
